# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllNYCSchools',
            fields=[
                ('ats_system_code', models.CharField(max_length=255, null=True, blank=True)),
                ('location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('location_name', models.CharField(max_length=255, null=True, blank=True)),
                ('beds_number', models.CharField(max_length=255, null=True, blank=True)),
                ('managed_by_name', models.CharField(max_length=255, null=True, blank=True)),
                ('location_type_description', models.CharField(max_length=255, null=True, blank=True)),
                ('location_category_description', models.CharField(max_length=255, null=True, blank=True)),
                ('grades', models.CharField(max_length=255, null=True, blank=True)),
                ('grades_final', models.CharField(max_length=255, null=True, blank=True)),
                ('open_date', models.DateField(null=True, blank=True)),
                ('status_description', models.CharField(max_length=255, null=True, blank=True)),
                ('building_code', models.CharField(max_length=255, null=True, blank=True)),
                ('primary_address', models.CharField(max_length=255, null=True, blank=True)),
                ('city', models.CharField(max_length=255, null=True, blank=True)),
                ('state_code', models.CharField(max_length=255, null=True, blank=True)),
                ('zip', models.CharField(max_length=255, null=True, blank=True)),
                ('principal_name', models.CharField(max_length=255, null=True, blank=True)),
                ('principal_title', models.CharField(max_length=255, null=True, blank=True)),
                ('principal_phone_number', models.CharField(max_length=255, null=True, blank=True)),
                ('fax_number', models.CharField(max_length=255, null=True, blank=True)),
                ('geographical_district_code', models.CharField(max_length=255, null=True, blank=True)),
                ('administrative_district_code', models.CharField(max_length=255, null=True, blank=True)),
                ('administrative_district_location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('administrative_district_name', models.CharField(max_length=255, null=True, blank=True)),
                ('superintendent', models.CharField(max_length=255, null=True, blank=True)),
                ('superintendent_location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('community_school_sup_name', models.CharField(max_length=255, null=True, blank=True)),
                ('cluster_name', models.CharField(max_length=255, null=True, blank=True)),
                ('cluster_location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('cluster_leader_name', models.CharField(max_length=255, null=True, blank=True)),
                ('cluster_leader_title', models.CharField(max_length=255, null=True, blank=True)),
                ('cluster_leader_phone', models.CharField(max_length=255, null=True, blank=True)),
                ('network_location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('network_name', models.CharField(max_length=255, null=True, blank=True)),
                ('network_leader', models.CharField(max_length=255, null=True, blank=True)),
                ('network_leader_phone', models.CharField(max_length=255, null=True, blank=True)),
                ('satif_code', models.CharField(max_length=255, null=True, blank=True)),
                ('satif_superintendent', models.CharField(max_length=255, null=True, blank=True)),
                ('highschool_network_location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('highschool_network_name', models.CharField(max_length=255, null=True, blank=True)),
                ('highschool_network_superintendent', models.CharField(max_length=255, null=True, blank=True)),
                ('operational_network_location_code', models.CharField(max_length=255, null=True, blank=True)),
                ('operational_network_name', models.CharField(max_length=255, null=True, blank=True)),
                ('operational_network_manager_name', models.CharField(max_length=255, null=True, blank=True)),
                ('operational_network_manager_phone', models.CharField(max_length=255, null=True, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'all_nyc_schools',
            },
        ),
        migrations.CreateModel(
            name='Radpa',
            fields=[
                ('school', models.CharField(max_length=255, db_column='dbn')),
                ('day_ofadm', models.DateField()),
                ('student_name', models.CharField(max_length=255)),
                ('st', models.CharField(max_length=255)),
                ('sx', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('student_id', models.IntegerField()),
                ('cur_grd', models.CharField(max_length=255)),
                ('cur_cls', models.CharField(max_length=255)),
                ('adm_grd', models.CharField(max_length=255)),
                ('adm_cls', models.CharField(max_length=255)),
                ('adm_cde', models.CharField(max_length=255)),
                ('adm_rea', models.CharField(max_length=255)),
                ('hm_lg', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('apt_flr', models.CharField(max_length=255)),
                ('zip_cde', models.CharField(max_length=255)),
                ('pob_cde', models.CharField(max_length=255)),
                ('geo_cde', models.CharField(max_length=255)),
                ('from_dbn', models.CharField(max_length=255)),
                ('recs_rcvd_sent', models.CharField(max_length=255)),
                ('documents_code', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_radpa',
            },
        ),
        migrations.CreateModel(
            name='Radpd',
            fields=[
                ('school', models.CharField(max_length=255, db_column='dbn', blank=True)),
                ('day_of_disch', models.DateField(null=True, blank=True)),
                ('student_name', models.CharField(max_length=255, blank=True)),
                ('sex', models.CharField(max_length=255, blank=True)),
                ('birth_dte', models.DateField(null=True, blank=True)),
                ('student_id', models.IntegerField(null=True, blank=True)),
                ('cur_grd', models.CharField(max_length=255, blank=True)),
                ('cur_cls', models.CharField(max_length=255, blank=True)),
                ('admission_dte', models.CharField(max_length=255, blank=True)),
                ('dis_cde', models.CharField(max_length=255, blank=True)),
                ('dis_reason_dipl_typ', models.CharField(max_length=255, blank=True)),
                ('new_street_address', models.CharField(max_length=255, blank=True)),
                ('apt_flr', models.CharField(max_length=255, blank=True)),
                ('zip_cde', models.CharField(max_length=255, blank=True)),
                ('pst_sec_pln', models.CharField(max_length=255, blank=True)),
                ('geo_cde', models.CharField(max_length=255, blank=True)),
                ('to_boro', models.CharField(max_length=255, blank=True)),
                ('dist', models.CharField(max_length=255, blank=True)),
                ('schl', models.CharField(max_length=255, blank=True)),
                ('con_frm_dis', models.CharField(max_length=255, blank=True)),
                ('recs_rcvd_sent', models.CharField(max_length=255, blank=True)),
                ('documents_code', models.CharField(max_length=255, blank=True)),
                ('tracking_date', models.DateField(null=True, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_radpd',
            },
        ),
        migrations.CreateModel(
            name='Radr',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('grd', models.CharField(max_length=255)),
                ('grd_level', models.CharField(max_length=255)),
                ('off_cls', models.CharField(max_length=255)),
                ('house_num', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('apt_num', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('res_boro', models.CharField(max_length=255)),
                ('res_dist', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('a_c_flag', models.CharField(max_length=255)),
                ('err_code', models.CharField(max_length=255)),
                ('dist_code', models.CharField(max_length=255)),
                ('non_res', models.CharField(max_length=255)),
                ('house_stat', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_radr',
            },
        ),
        migrations.CreateModel(
            name='Rbir',
            fields=[
                ('school', models.CharField(max_length=255, db_column='ddbnnn', blank=True)),
                ('last_name', models.CharField(max_length=255, blank=True)),
                ('first_name', models.CharField(max_length=255, blank=True)),
                ('student_id', models.IntegerField(null=True, blank=True)),
                ('sex', models.CharField(max_length=255, blank=True)),
                ('birth_dt', models.DateField(null=True, blank=True)),
                ('off_cls', models.CharField(max_length=255, blank=True)),
                ('grd_cd', models.CharField(max_length=255, blank=True)),
                ('grd_lvl', models.CharField(max_length=255, blank=True)),
                ('street_number', models.CharField(max_length=255, blank=True)),
                ('street', models.CharField(max_length=255, blank=True)),
                ('apt', models.CharField(max_length=255, blank=True)),
                ('city', models.CharField(max_length=255, blank=True)),
                ('st', models.CharField(max_length=255, blank=True)),
                ('zip', models.CharField(max_length=255, blank=True)),
                ('home_phone', models.CharField(max_length=255, blank=True)),
                ('adult_last_1', models.CharField(max_length=255, blank=True)),
                ('adult_first_1', models.CharField(max_length=255, blank=True)),
                ('adult_phone_1', models.CharField(max_length=255, blank=True)),
                ('adult_last_2', models.CharField(max_length=255, blank=True)),
                ('adult_first_2', models.CharField(max_length=255, blank=True)),
                ('adult_phone_2', models.CharField(max_length=255, blank=True)),
                ('adult_last_3', models.CharField(max_length=255, blank=True)),
                ('adult_first_3', models.CharField(max_length=255, blank=True)),
                ('adult_phone_3', models.CharField(max_length=255, blank=True)),
                ('student_phone', models.CharField(max_length=255, blank=True)),
                ('meal_cde', models.CharField(max_length=255, blank=True)),
                ('ytd_attd_pct', models.CharField(max_length=255, blank=True)),
                ('email', models.CharField(max_length=255, blank=True)),
                ('tracking_date', models.DateField(null=True, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rbir',
            },
        ),
        migrations.CreateModel(
            name='Rdgs',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('d_o_b', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('off_cls', models.CharField(max_length=255)),
                ('spec_ed', models.CharField(max_length=255)),
                ('ethnic', models.CharField(max_length=255)),
                ('ell', models.CharField(max_length=255)),
                ('econ_dis', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rdgs',
            },
        ),
        migrations.CreateModel(
            name='Rhil',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=255)),
                ('grd_cde', models.CharField(max_length=255)),
                ('grd_lvl', models.CharField(max_length=255)),
                ('off_cls', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('admission_date', models.DateField()),
                ('immun_stat', models.CharField(max_length=255)),
                ('excludable_date', models.CharField(max_length=255)),
                ('immun_type', models.CharField(max_length=255)),
                ('incmpl', models.CharField(max_length=255)),
                ('exempt_code', models.CharField(max_length=255)),
                ('exempt_end_date', models.DateField()),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rhil',
            },
        ),
        migrations.CreateModel(
            name='Rhin',
            fields=[
                ('school', models.CharField(max_length=255, db_column='dbn')),
                ('student_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=255)),
                ('grade_code', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('off_class', models.CharField(max_length=255)),
                ('health_ins_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rhin',
            },
        ),
        migrations.CreateModel(
            name='Rmel',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('official_class', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('home_room', models.CharField(max_length=255)),
                ('meal_code', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('incomplete_reasons', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rmel',
            },
        ),
        migrations.CreateModel(
            name='Rnec',
            fields=[
                ('school', models.CharField(max_length=255, db_column='dbn')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('grade_code', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('off_class', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('hispanic', models.CharField(max_length=255)),
                ('american_indian_alaskan', models.CharField(max_length=255)),
                ('asian', models.CharField(max_length=255)),
                ('hawaiian_pacific_islander', models.CharField(max_length=255)),
                ('black', models.CharField(max_length=255)),
                ('white', models.CharField(max_length=255)),
                ('old_ethnic_code', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rnec',
            },
        ),
        migrations.CreateModel(
            name='Rocl',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('ocl', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('loc', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('advisor', models.CharField(max_length=255)),
                ('staff_1', models.CharField(max_length=255)),
                ('staff_2', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('gl', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rocl',
            },
        ),
        migrations.CreateModel(
            name='Rpob',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('grade', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('official_class', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('x_coded', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('home_language_code', models.CharField(max_length=255)),
                ('geo_code', models.CharField(max_length=255)),
                ('first_enter_nyc_date', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rpob',
            },
        ),
        migrations.CreateModel(
            name='Rsfm',
            fields=[
                ('school', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('class_field', models.CharField(max_length=255, db_column='class')),
                ('admit_date', models.DateField()),
                ('admit_code', models.CharField(max_length=255)),
                ('admit_reason', models.CharField(max_length=255)),
                ('prev_school', models.CharField(max_length=255)),
                ('prev_grade', models.CharField(max_length=255)),
                ('prev_level', models.CharField(max_length=255)),
                ('prev_class', models.CharField(max_length=255)),
                ('prev_admit_date', models.DateField()),
                ('prev_admit_code', models.CharField(max_length=255)),
                ('prev_discharge_date', models.DateField()),
                ('prev_discharge_code', models.CharField(max_length=255)),
                ('tracking_date', models.DateField()),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rsfm',
            },
        ),
        migrations.CreateModel(
            name='Rspd',
            fields=[
                ('network', models.CharField(max_length=255, blank=True)),
                ('cluster', models.CharField(max_length=255, blank=True)),
                ('cfn', models.CharField(max_length=255, blank=True)),
                ('school', models.CharField(max_length=255, db_column='school_dbn', blank=True)),
                ('student_id', models.IntegerField(null=True, blank=True)),
                ('last_name', models.CharField(max_length=255, blank=True)),
                ('first_name', models.CharField(max_length=255, blank=True)),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('sex', models.CharField(max_length=255, blank=True)),
                ('grade', models.CharField(max_length=255, blank=True)),
                ('level', models.CharField(max_length=255, blank=True)),
                ('class_field', models.CharField(max_length=255, db_column='class', blank=True)),
                ('cap_class', models.CharField(max_length=255, blank=True)),
                ('cap_data_as_of_dte', models.DateField(null=True, blank=True)),
                ('first_attend_dte', models.DateField(null=True, blank=True)),
                ('conference_dte', models.DateField(null=True, blank=True)),
                ('cap_authorize_dte', models.DateField(null=True, blank=True)),
                ('cap_disc_dte', models.DateField(null=True, blank=True)),
                ('prog_recom_cde', models.CharField(max_length=255, blank=True)),
                ('prog_recom_desc', models.CharField(max_length=255, blank=True)),
                ('serv_ctgry', models.CharField(max_length=255, blank=True)),
                ('serv_description', models.CharField(max_length=255, blank=True)),
                ('prds_per_wk', models.CharField(max_length=255, blank=True)),
                ('full_part_time', models.CharField(max_length=255, blank=True)),
                ('disab_cde', models.CharField(max_length=255, blank=True)),
                ('disab_desc', models.CharField(max_length=255, blank=True)),
                ('tm_code_1', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_1', models.CharField(max_length=255, blank=True)),
                ('tm_code_2', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_2', models.CharField(max_length=255, blank=True)),
                ('tm_code_3', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_3', models.CharField(max_length=255, blank=True)),
                ('tm_code_4', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_4', models.CharField(max_length=255, blank=True)),
                ('tm_code_5', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_5', models.CharField(max_length=255, blank=True)),
                ('tm_code_6', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_6', models.CharField(max_length=255, blank=True)),
                ('tm_code_7', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_7', models.CharField(max_length=255, blank=True)),
                ('tm_code_8', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_8', models.CharField(max_length=255, blank=True)),
                ('tm_code_9', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_9', models.CharField(max_length=255, blank=True)),
                ('tm_code_10', models.CharField(max_length=255, blank=True)),
                ('test_mod_description_10', models.CharField(max_length=255, blank=True)),
                ('promo_cde', models.CharField(max_length=255, blank=True)),
                ('promo_desc', models.CharField(max_length=255, blank=True)),
                ('wheelchair_yn', models.CharField(max_length=255, blank=True)),
                ('cap_school', models.CharField(max_length=255, blank=True)),
                ('class_in_cap', models.CharField(max_length=255, blank=True)),
                ('te_code', models.CharField(max_length=255, blank=True)),
                ('te_description', models.CharField(max_length=255, blank=True)),
                ('cap_biling_cde', models.CharField(max_length=255, blank=True)),
                ('cap_biling_desc', models.CharField(max_length=255, blank=True)),
                ('rs_code_1', models.CharField(max_length=255, blank=True)),
                ('rs_description_1', models.CharField(max_length=255, blank=True)),
                ('freq_cde_1', models.CharField(max_length=255, blank=True)),
                ('dur_cde_1', models.CharField(max_length=255, blank=True)),
                ('gp_code_1', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_1', models.DateField(null=True, blank=True)),
                ('rs_code_2', models.CharField(max_length=255, blank=True)),
                ('rs_description_2', models.CharField(max_length=255, blank=True)),
                ('freq_cde_2', models.CharField(max_length=255, blank=True)),
                ('dur_cde_2', models.CharField(max_length=255, blank=True)),
                ('gp_code_2', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_2', models.DateField(null=True, blank=True)),
                ('rs_code_3', models.CharField(max_length=255, blank=True)),
                ('rs_description_3', models.CharField(max_length=255, blank=True)),
                ('freq_cde_3', models.CharField(max_length=255, blank=True)),
                ('dur_cde_3', models.CharField(max_length=255, blank=True)),
                ('gp_code_3', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_3', models.DateField(null=True, blank=True)),
                ('rs_code_4', models.CharField(max_length=255, blank=True)),
                ('rs_description_4', models.CharField(max_length=255, blank=True)),
                ('freq_cde_4', models.CharField(max_length=255, blank=True)),
                ('dur_cde_4', models.CharField(max_length=255, blank=True)),
                ('gp_code_4', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_4', models.DateField(null=True, blank=True)),
                ('rs_code_5', models.CharField(max_length=255, blank=True)),
                ('rs_description_5', models.CharField(max_length=255, blank=True)),
                ('freq_cde_5', models.CharField(max_length=255, blank=True)),
                ('dur_cde_5', models.CharField(max_length=255, blank=True)),
                ('gp_code_5', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_5', models.DateField(null=True, blank=True)),
                ('rs_code_6', models.CharField(max_length=255, blank=True)),
                ('rs_description_6', models.CharField(max_length=255, blank=True)),
                ('freq_cde_6', models.CharField(max_length=255, blank=True)),
                ('dur_cde_6', models.CharField(max_length=255, blank=True)),
                ('gp_code_6', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_6', models.DateField(null=True, blank=True)),
                ('rs_code_7', models.CharField(max_length=255, blank=True)),
                ('rs_description_7', models.CharField(max_length=255, blank=True)),
                ('freq_cde_7', models.CharField(max_length=255, blank=True)),
                ('dur_cde_7', models.CharField(max_length=255, blank=True)),
                ('gp_code_7', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_7', models.DateField(null=True, blank=True)),
                ('rs_code_8', models.CharField(max_length=255, blank=True)),
                ('rs_description_8', models.CharField(max_length=255, blank=True)),
                ('freq_cde_8', models.CharField(max_length=255, blank=True)),
                ('dur_cde_8', models.CharField(max_length=255, blank=True)),
                ('gp_code_8', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_8', models.DateField(null=True, blank=True)),
                ('rs_code_9', models.CharField(max_length=255, blank=True)),
                ('rs_description_9', models.CharField(max_length=255, blank=True)),
                ('freq_cde_9', models.CharField(max_length=255, blank=True)),
                ('dur_cde_9', models.CharField(max_length=255, blank=True)),
                ('gp_code_9', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_9', models.DateField(null=True, blank=True)),
                ('rs_code_10', models.CharField(max_length=255, blank=True)),
                ('rs_description_10', models.CharField(max_length=255, blank=True)),
                ('freq_cde_10', models.CharField(max_length=255, blank=True)),
                ('dur_cde_10', models.CharField(max_length=255, blank=True)),
                ('gp_code_10', models.CharField(max_length=255, blank=True)),
                ('first_attd_dte_10', models.DateField(null=True, blank=True)),
                ('tracking_date', models.DateField(null=True, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rspd',
            },
        ),
        migrations.CreateModel(
            name='Rtrr',
            fields=[
                ('school', models.CharField(max_length=255, db_column='dbn', blank=True)),
                ('name', models.CharField(max_length=255, blank=True)),
                ('student_id', models.IntegerField(null=True, blank=True)),
                ('dob', models.DateField(null=True, blank=True)),
                ('sex', models.CharField(max_length=255, blank=True)),
                ('grade', models.CharField(max_length=255, blank=True)),
                ('grade_level', models.CharField(max_length=255, blank=True)),
                ('off_class', models.CharField(max_length=255, blank=True)),
                ('opt_sch', models.CharField(max_length=255, blank=True)),
                ('opt_grd', models.CharField(max_length=255, blank=True)),
                ('distance', models.CharField(max_length=255, blank=True)),
                ('metro_crd_type', models.CharField(max_length=255, blank=True)),
                ('metro_crd_num', models.CharField(max_length=255, blank=True)),
                ('bus_stop', models.CharField(max_length=255, blank=True)),
                ('spec_ed', models.CharField(max_length=255, blank=True)),
                ('var_no', models.CharField(max_length=255, blank=True)),
                ('trans_stat', models.CharField(max_length=255, blank=True)),
                ('address', models.CharField(max_length=255, blank=True)),
                ('city_state', models.CharField(max_length=255, blank=True)),
                ('zip_cde', models.CharField(max_length=255, blank=True)),
                ('street_cde', models.CharField(max_length=255, blank=True)),
                ('phone_num', models.CharField(max_length=255, blank=True)),
                ('change_date', models.DateField(null=True, blank=True)),
                ('tracking_date', models.DateField(null=True, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'ats_rtrr',
            },
        ),
    ]
